# Generated by Django 2.2 on 2020-09-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('text', models.TextField()),
                ('title', models.TextField()),
                ('link', models.IntegerField()),
            ],
        ),
    ]
